from app.prompts.llm_prompts import (
    ROUTER_SYSTEM_PROMPT,
    CHITCHAT_SYSTEM_PROMPT,
    CONTEXTUALIZE_QUERY_SYSTEM_PROMPT,
    EXPAND_QUERY_SYSTEM_PROMPT,
    GENERATE_ANSWER_SYSTEM_PROMPT,
    RAG_USER_PROMPT,
    HANDOFF_SYSTEM_PROMPT,
)

__all__ = [
    "ROUTER_SYSTEM_PROMPT",
    "CHITCHAT_SYSTEM_PROMPT",
    "CONTEXTUALIZE_QUERY_SYSTEM_PROMPT",
    "EXPAND_QUERY_SYSTEM_PROMPT",
    "GENERATE_ANSWER_SYSTEM_PROMPT",
    "RAG_USER_PROMPT",
    "HANDOFF_SYSTEM_PROMPT",
]
