name: monitoring
services:
  dozzle:
    container_name: veridata.dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - 4022:8080
    networks:
      veridata.network:
        aliases:
          - veridata.dozzle
    restart: unless-stopped

networks:
  veridata.network:
    external: true
