import os
import logging
from contextlib import contextmanager, asynccontextmanager
from typing import Generator, AsyncGenerator
import psycopg
from psycopg_pool import ConnectionPool
from sqlalchemy.ext.asyncio import create_async_engine, AsyncEngine, async_sessionmaker, AsyncSession

logger = logging.getLogger(__name__)

# Singleton pool
_pool: ConnectionPool = None
_engine: AsyncEngine = None
_SessionLocal: async_sessionmaker = None

def get_engine() -> AsyncEngine:
    global _engine
    global _SessionLocal
    if _engine is None:
        db_url = os.getenv("DATABASE_URL")
        if not db_url:
            raise ValueError("DATABASE_URL environment variable is not set")

        # SQLAlchemy 2.0 with psycopg v3 requires the +psycopg dialect
        if db_url.startswith("postgresql://"):
            db_url = db_url.replace("postgresql://", "postgresql+psycopg://", 1)

        # Async requires the asyncpg or psycopg async driver
        # psycopg3 supports async, we just need to ensure the dialect reflects it if needed,
        # but SQLAlchemy natively handles async with `postgresql+psycopg` when using create_async_engine

        _engine = create_async_engine(db_url, echo=False, pool_pre_ping=True)
        _SessionLocal = async_sessionmaker(_engine, expire_on_commit=False, class_=AsyncSession)
    return _engine

def get_pool() -> ConnectionPool:
    global _pool
    if _pool is None:
        db_url = os.getenv("DATABASE_URL")
        if not db_url:
            raise ValueError("DATABASE_URL environment variable is not set")
        _pool = ConnectionPool(conninfo=db_url, min_size=1, max_size=10)
    return _pool

@contextmanager
def get_db() -> Generator[psycopg.Connection, None, None]:
    """Get a database connection from the pool."""
    pool = get_pool()
    with pool.connection() as conn:
        yield conn

@asynccontextmanager
async def get_session() -> AsyncGenerator[AsyncSession, None]:
    """Get an asynchronous SQLAlchemy ORM session."""
    get_engine() # ensure engine and SessionLocal are configured
    async with _SessionLocal() as session:
        yield session

def init_db():
    """Initialize the database schema."""
    logger.info("Initializing database schema...")

    db_url = os.getenv("DATABASE_URL")
    if not db_url:
        logger.error("DATABASE_URL environment variable is not set. Skipping DB Init.")
        return

    # To run synchronous setup scripts, we can use an ephemeral synchronous psycopg connection
    db_url_sync = db_url.replace("postgresql+psycopg://", "postgresql://", 1)

    with psycopg.connect(conninfo=db_url_sync) as conn:
        with conn.cursor() as cur:
            # Enable pgvector extension
            cur.execute("CREATE EXTENSION IF NOT EXISTS vector;")

            # 1. TENANTS (The Parent Table)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS tenants (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    slug VARCHAR(255) NOT NULL UNIQUE,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );
            """)

            # 2. SUBSCRIPTIONS
            cur.execute("""
                CREATE TABLE IF NOT EXISTS subscriptions (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id INTEGER NOT NULL,
                    is_active BOOLEAN NOT NULL DEFAULT true,
                    quota_limit BIGINT NOT NULL DEFAULT 0,
                    usage_count BIGINT NOT NULL DEFAULT 0,
                    start_dat TIMESTAMPTZ NOT NULL,
                    end_date TIMESTAMPTZ NOT NULL,
                    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
                );
            """)

            # 3. CONFIGURATIONS
            cur.execute("""
                CREATE TABLE IF NOT EXISTS configurations (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id INTEGER NOT NULL,
                    settings JSONB,
                    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
                );
            """)

            # 4. SERVICES
            cur.execute("""
                CREATE TABLE IF NOT EXISTS services (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id INTEGER NOT NULL,
                    name VARCHAR(255) NOT NULL,
                    url VARCHAR(255),
                    api_key VARCHAR(255),
                    account_id VARCHAR(255),
                    settings JSONB,
                    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
                );
            """)

            # 5. CONTACT_MAPPINGS
            cur.execute("""
                CREATE TABLE IF NOT EXISTS contact_mappings (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id INTEGER NOT NULL,
                    chatwoot_contact_id INTEGER NOT NULL,
                    service_name VARCHAR(255) NOT NULL,
                    external_id VARCHAR(255) NOT NULL,
                    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
                );
            """)

            # 6. Drop CHAT_SESSION (now deprecated in favor of is_summarized in messages)
            cur.execute("DROP TABLE IF EXISTS chat_session CASCADE;")

            # 6b. CHAT_MESSAGES
            cur.execute("""
                CREATE TABLE IF NOT EXISTS chat_messages (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id INTEGER NOT NULL,
                    chatwoot_account_id INTEGER NOT NULL,
                    chatwoot_conversation_id INTEGER NOT NULL,
                    message_id INTEGER NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE,
                    CONSTRAINT uq_chat_message_conversation UNIQUE("tenant_id", "chatwoot_account_id", "chatwoot_conversation_id")
                );
            """)

            # Create indices
            cur.execute("CREATE INDEX IF NOT EXISTS idx_subscriptions_tenant ON subscriptions(tenant_id);")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_services_tenant ON services(tenant_id);")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_chat_messages_tenant ON chat_messages(tenant_id);")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_chat_messages_conv ON chat_messages(chatwoot_conversation_id);")

            # 7. GLOBAL_CONFIGS
            cur.execute("""
                CREATE TABLE IF NOT EXISTS global_configs (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    settings JSONB
                );
            """)

            # Create documents table (RAG specific)
            dim = 3072
            cur.execute(f"""
                CREATE TABLE IF NOT EXISTS documents (
                    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                    tenant_id INTEGER REFERENCES tenants(id) ON DELETE CASCADE,
                    parent_id UUID REFERENCES documents(id) ON DELETE CASCADE,
                    filename VARCHAR(255) NOT NULL,
                    content TEXT NOT NULL,
                    embedding vector({dim}),
                    fts tsvector GENERATED ALWAYS AS (to_tsvector('english', coalesce(content, ''))) STORED,
                    metadata_ JSONB,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                );
            """)
            cur.execute("CREATE INDEX IF NOT EXISTS documents_tenant_id_idx ON documents (tenant_id);")
            cur.execute("CREATE INDEX IF NOT EXISTS documents_parent_id_idx ON documents (parent_id);")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_documents_fts ON documents USING GIN (fts);")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_documents_metadata ON documents USING GIN (metadata_);")

            conn.commit()

    logger.info("Database schema initialized.")

def close_pool():
    global _pool
    if _pool is not None:
        _pool.close()
        _pool = None
