"""
Database bootstrap SQL.

This is intentionally separate from migrations. `init_db` executes these
idempotent statements for local/simple deployments.
"""

CREATE_VECTOR_EXTENSION_QUERY = "CREATE EXTENSION IF NOT EXISTS vector;"

CREATE_TENANTS_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS tenants (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
"""

CREATE_SUBSCRIPTIONS_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS subscriptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    quota_limit BIGINT NOT NULL DEFAULT 0,
    usage_count BIGINT NOT NULL DEFAULT 0,
    start_dat TIMESTAMPTZ NOT NULL,
    end_date TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
);
"""

CREATE_CONFIGURATIONS_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS configurations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    settings JSONB,
    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
);
"""

CREATE_SERVICES_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS services (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    url VARCHAR(255),
    api_key VARCHAR(255),
    account_id VARCHAR(255),
    settings JSONB,
    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
);
"""

CREATE_CONTACT_MAPPINGS_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS contact_mappings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    chatwoot_contact_id INTEGER NOT NULL,
    service_name VARCHAR(255) NOT NULL,
    external_id VARCHAR(255) NOT NULL,
    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
);
"""

DROP_CHAT_SESSION_TABLE_QUERY = "DROP TABLE IF EXISTS chat_session CASCADE;"

CREATE_CHAT_MESSAGES_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS chat_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INTEGER NOT NULL,
    chatwoot_account_id INTEGER NOT NULL,
    chatwoot_conversation_id INTEGER NOT NULL,
    message_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE,
    CONSTRAINT uq_chat_message_conversation UNIQUE("tenant_id", "chatwoot_account_id", "chatwoot_conversation_id")
);
"""

CREATE_GLOBAL_CONFIGS_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS global_configs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settings JSONB
);
"""

CREATE_DOCUMENTS_TABLE_QUERY = """
CREATE TABLE IF NOT EXISTS documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id INTEGER REFERENCES tenants(id) ON DELETE CASCADE,
    parent_id UUID REFERENCES documents(id) ON DELETE CASCADE,
    filename VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    embedding vector(3072),
    fts tsvector GENERATED ALWAYS AS (to_tsvector('english', coalesce(content, ''))) STORED,
    metadata_ JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
"""

SCHEMA_BOOTSTRAP_QUERIES = (
    CREATE_VECTOR_EXTENSION_QUERY,
    CREATE_TENANTS_TABLE_QUERY,
    CREATE_SUBSCRIPTIONS_TABLE_QUERY,
    CREATE_CONFIGURATIONS_TABLE_QUERY,
    CREATE_SERVICES_TABLE_QUERY,
    CREATE_CONTACT_MAPPINGS_TABLE_QUERY,
    DROP_CHAT_SESSION_TABLE_QUERY,
    CREATE_CHAT_MESSAGES_TABLE_QUERY,
    CREATE_GLOBAL_CONFIGS_TABLE_QUERY,
    CREATE_DOCUMENTS_TABLE_QUERY,
)

SCHEMA_INDEX_QUERIES = (
    "CREATE INDEX IF NOT EXISTS idx_subscriptions_tenant ON subscriptions(tenant_id);",
    "CREATE INDEX IF NOT EXISTS idx_services_tenant ON services(tenant_id);",
    "CREATE INDEX IF NOT EXISTS idx_chat_messages_tenant ON chat_messages(tenant_id);",
    "CREATE INDEX IF NOT EXISTS idx_chat_messages_conv ON chat_messages(chatwoot_conversation_id);",
    "CREATE INDEX IF NOT EXISTS documents_tenant_id_idx ON documents (tenant_id);",
    "CREATE INDEX IF NOT EXISTS documents_parent_id_idx ON documents (parent_id);",
    "CREATE INDEX IF NOT EXISTS idx_documents_fts ON documents USING GIN (fts);",
    "CREATE INDEX IF NOT EXISTS idx_documents_metadata ON documents USING GIN (metadata_);",
)
