services:
  wp-legado:
    image: wordpress:latest
    container_name: wp-legado
    ports:
      - "4023:80"
    environment:
      WORDPRESS_DB_HOST: db-legado
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','https://dev-legacy.veridatapro.com');
        define('WP_SITEURL','https://dev-legacy.veridatapro.com');
        define('FORCE_SSL_ADMIN', true);
        $$_SERVER['HTTPS'] = 'on';
    volumes:
      - ./veridata-sso.php:/var/www/html/wp-content/mu-plugins/veridata-sso.php
    networks:
      veridata.network:
        aliases:
          - veridata.wp

  db-legado:
    image: mysql:8.0
    container_name: db-legado
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root
    networks:
      - veridata.network

networks:
  veridata.network:
    external: true
