"""add status and last_activity_at to chat_sessions

Revision ID: 43fff4508da9
Revises: ccaea338ac3a
Create Date: 2026-02-20 20:58:55.375560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43fff4508da9'
down_revision: Union[str, Sequence[str], None] = 'ccaea338ac3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('status', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_chat_sessions_last_activity_at'), 'chat_sessions', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_status'), 'chat_sessions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_status'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_last_activity_at'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'last_activity_at')
    op.drop_column('chat_sessions', 'status')
    # ### end Alembic commands ###
