-- 1. TENANTS (The Parent Table)
CREATE TABLE IF NOT EXISTS "tenants" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "slug" VARCHAR(255) NOT NULL UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. SUBSCRIPTIONS
CREATE TABLE IF NOT EXISTS "subscriptions" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tenant_id" INTEGER NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "quota_limit" BIGINT NOT NULL DEFAULT 0,
    "usage_count" BIGINT NOT NULL DEFAULT 0,
    "start_dat" TIMESTAMPTZ NOT NULL,
    "end_date" TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
);

-- 3. CONFIGURATIONS
CREATE TABLE IF NOT EXISTS "configurations" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tenant_id" INTEGER NOT NULL,
    "settings" JSONB,
    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
);

-- 4. SERVICES
CREATE TABLE IF NOT EXISTS "services" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tenant_id" INTEGER NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "url" VARCHAR(255),
    "api_key" VARCHAR(255),
    "account_id" VARCHAR(255),
    "settings" JSONB,
    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
);

-- 5. CONTACT_MAPPINGS
CREATE TABLE IF NOT EXISTS "contact_mappings" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tenant_id" INTEGER NOT NULL,
    "chatwoot_contact_id" INTEGER NOT NULL,
    "service_name" VARCHAR(255) NOT NULL,
    "external_id" VARCHAR(255) NOT NULL,
    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
);

-- 6. CHAT_SESSION
CREATE TABLE IF NOT EXISTS "chat_session" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tenant_id" INTEGER NOT NULL,
    "last_summarized_message_id" INTEGER NOT NULL DEFAULT 0,
    "last_private_summarized_message_id" INTEGER NOT NULL DEFAULT 0,
    "chatwoot_account_id" INTEGER NOT NULL,
    "chatwoot_conversation_id" INTEGER NOT NULL,
    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
);

-- Optional: Indexing for performance (Highly recommended for Integration services)
CREATE INDEX idx_subscriptions_tenant ON "subscriptions"("tenant_id");
CREATE INDEX idx_services_tenant ON "services"("tenant_id");
CREATE INDEX idx_chat_session_tenant ON "chat_session"("tenant_id");