import os
import logging
from contextlib import contextmanager
from typing import Generator
import psycopg
from psycopg_pool import ConnectionPool
from sqlalchemy import create_engine
from sqlalchemy.engine import Engine

logger = logging.getLogger(__name__)

# Singleton pool
_pool: ConnectionPool = None
_engine: Engine = None

def get_engine() -> Engine:
    global _engine
    if _engine is None:
        db_url = os.getenv("DATABASE_URL")
        if not db_url:
            raise ValueError("DATABASE_URL environment variable is not set")

        # SQLAlchemy 2.0 with psycopg v3 requires the +psycopg dialect
        if db_url.startswith("postgresql://"):
            db_url = db_url.replace("postgresql://", "postgresql+psycopg://", 1)

        _engine = create_engine(db_url)
    return _engine

def get_pool() -> ConnectionPool:
    global _pool
    if _pool is None:
        db_url = os.getenv("DATABASE_URL")
        if not db_url:
            raise ValueError("DATABASE_URL environment variable is not set")
        _pool = ConnectionPool(conninfo=db_url, min_size=1, max_size=10)
    return _pool

@contextmanager
def get_db() -> Generator[psycopg.Connection, None, None]:
    """Get a database connection from the pool."""
    pool = get_pool()
    with pool.connection() as conn:
        yield conn

def init_db():
    """Initialize the database schema."""
    logger.info("Initializing database schema...")
    with get_db() as conn:
        with conn.cursor() as cur:
            # Enable pgvector extension
            cur.execute("CREATE EXTENSION IF NOT EXISTS vector;")

            # [DEVELOPMENT ONLY] Drop existing tables to simplify PK change
            # logger.warning("Dropping tables for PK refactor (Development Phase)")
            # cur.execute("DROP TABLE IF EXISTS documents CASCADE;")
            # cur.execute("DROP TABLE IF EXISTS tenants CASCADE;")

            # 1. TENANTS (The Parent Table)
            cur.execute("""
                CREATE TABLE IF NOT EXISTS tenants (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    slug VARCHAR(255) NOT NULL UNIQUE,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                );
            """)

            # 2. SUBSCRIPTIONS
            cur.execute("""
                CREATE TABLE IF NOT EXISTS subscriptions (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id INTEGER NOT NULL,
                    is_active BOOLEAN NOT NULL DEFAULT true,
                    quota_limit BIGINT NOT NULL DEFAULT 0,
                    usage_count BIGINT NOT NULL DEFAULT 0,
                    start_dat TIMESTAMPTZ NOT NULL,
                    end_date TIMESTAMPTZ NOT NULL,
                    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
                );
            """)

            # 3. CONFIGURATIONS
            cur.execute("""
                CREATE TABLE IF NOT EXISTS configurations (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id INTEGER NOT NULL,
                    settings JSONB,
                    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
                );
            """)

            # 4. SERVICES
            cur.execute("""
                CREATE TABLE IF NOT EXISTS services (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id INTEGER NOT NULL,
                    name VARCHAR(255) NOT NULL,
                    url VARCHAR(255),
                    api_key VARCHAR(255),
                    account_id VARCHAR(255),
                    settings JSONB,
                    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
                );
            """)

            # 5. CONTACT_MAPPINGS
            cur.execute("""
                CREATE TABLE IF NOT EXISTS contact_mappings (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id INTEGER NOT NULL,
                    chatwoot_contact_id INTEGER NOT NULL,
                    service_name VARCHAR(255) NOT NULL,
                    external_id VARCHAR(255) NOT NULL,
                    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
                );
            """)

            # 6. CHAT_SESSION
            cur.execute("""
                CREATE TABLE IF NOT EXISTS chat_session (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id INTEGER NOT NULL,
                    last_summarized_message_id INTEGER NOT NULL DEFAULT 0,
                    last_private_summarized_message_id INTEGER NOT NULL DEFAULT 0,
                    chatwoot_account_id INTEGER NOT NULL,
                    chatwoot_conversation_id INTEGER NOT NULL,
                    CONSTRAINT fk_tenant FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE
                );
            """)

            # Create indices
            cur.execute("CREATE INDEX IF NOT EXISTS idx_subscriptions_tenant ON subscriptions(tenant_id);")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_services_tenant ON services(tenant_id);")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_chat_session_tenant ON chat_session(tenant_id);")

            # Create documents table (RAG specific)
            dim = 3072
            cur.execute(f"""
                CREATE TABLE IF NOT EXISTS documents (
                    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                    tenant_id INTEGER REFERENCES tenants(id) ON DELETE CASCADE,
                    filename VARCHAR(255) NOT NULL,
                    content TEXT NOT NULL,
                    embedding vector({dim}),
                    fts tsvector GENERATED ALWAYS AS (to_tsvector('english', coalesce(content, ''))) STORED,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                );
            """)
            cur.execute("CREATE INDEX IF NOT EXISTS documents_tenant_id_idx ON documents (tenant_id);")
            cur.execute("CREATE INDEX IF NOT EXISTS idx_documents_fts ON documents USING GIN (fts);")

    logger.info("Database schema initialized.")

def close_pool():
    global _pool
    if _pool is not None:
        _pool.close()
        _pool = None
